# Generated by Django 4.1.3 on 2022-11-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('institute_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('no_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopRankers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('video', models.CharField(max_length=40)),
                ('institute_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formApp.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('institute_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formApp.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('institute_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formApp.partner')),
            ],
        ),
        migrations.CreateModel(
            name='DemoVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=20)),
                ('institute_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formApp.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('institute_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formApp.partner')),
            ],
        ),
    ]
